<trace> ::= <s0> | <s1> | <s6> | <s7> | <s0><s0n> | <s1><s1n> | <s6><s6n> | <s7><s7n>
<vars>  ::= 'f,h,o'
<s0>    ::= '0,0,0'
<s1>    ::= '0,0,1'
<s2>    ::= '0,1,0'
<s3>    ::= '0,1,1'
<s6>    ::= '1,1,0'
<s7>    ::= '1,1,1'
<s0n>   ::= <s0> | <s1> | <s2> | <s0><s0n> | <s1><s1n> | <s2><s2n>
<s1n>   ::= <s1> | <s0> | <s1><s1n> | <s0><s0n>
<s2n>   ::= <s2> | <s3> | <s6> | <s2><s2n> | <s3><s3n> | <s6><s6n>
<s3n>   ::= <s3> | <s2> | <s1> | <s3><s3n> | <s2><s2n> | <s1><s1n>
<s6n>   ::= <s6> | <s7> | <s6><s6n> | <s7><s7n>
<s7n>   ::= <s7> | <s6> | <s3> | <s7><s7n> | <s6><s6n> | <s3><s3n>
